stages:
  - docker-build

variables:
  IMAGE_NAME: registry.gitlab.com/qs-portfolio/backend:latest

docker-build:
  stage: docker-build
  script:
    - docker build -t $IMAGE_NAME .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $IMAGE_NAME
  only:
    - main