stages:
  - test

test_aws:
  stage: test
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  variables:
    AWS_DEFAULT_REGION: us-east-1       # your EKS region
    CLUSTER_NAME: my-eks-cluster        # your EKS cluster name
  script:
    # Configure AWS CLI
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION

    # Check AWS account info
    - aws sts get-caller-identity
  only:
    - main