stages:
  - test

test_aws_connection:
  stage: test
  image: amazon/aws-cli:latest
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_REGION: $AWS_REGION
  script:
    - aws sts get-caller-identity