stages:
  - test

test_aws_connection:
  stage: test
  image: amazon/aws-cli:latest
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  script:
    - echo "Testing AWS connection..."
  only:
    - main
    - test