jwt_secret: ${JWT_SECRET}
polygon_api_key: ${POLYGON_API_KEY}

spring:
  datasource:
    url: jdbc:postgresql://portfolio-stagging.chys24quknwb.eu-north-1.rds.amazonaws.com:5432/postgres
    username: portfolio
    password: ${DB_PASSWORD}