jwt_secret: e113ae30-637c-4314-8215-6384b117aa3d
polygon_api_key: ${POLYGON_API_KEY}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: portfolio
    password: portfolio

management:
  endpoints:
    web:
      exposure:
        include: health,info
