jwt_secret: e113ae30-637c-4314-8215-6384b117aa3d
polygon_api_key: SECRET_KEY
finnhub_api_key: SECRET_KEY

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: portfolio
    password: portfolio
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: local-consumer-group

management:
  endpoints:
    web:
      exposure:
        include: health,info