jwt_secret: ${JWT_SECRET}
polygon_api_key: ${POLYGON_API_KEY}
finnhub_api_key: ${FINNHUB_API_KEY}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}:9092
    consumer:
      group-id: prod-consumer-group