jwt_secret: ${JWT_SECRET}
polygon_api_key: ${POLYGON_API_KEY}

spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:6543/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}