apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::054799132871:user/EKS-Deployer
      username: eks-deployer
      groups:
        - system:masters