apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      environment: staging
  template:
    metadata:
      labels:
        app: backend
        environment: staging
    spec:
      containers:
        - name: backend
          image: 958972464858.dkr.ecr.eu-north-1.amazonaws.com/backend:staging
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-staging-service
spec:
  type: ClusterIP
  selector:
    app: backend
    environment: staging
  ports:
    - port: 8080
      targetPort: 8080