apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      environment: staging
  template:
    metadata:
      labels:
        app: backend
        environment: staging
    spec:
      containers:
        - name: backend
          image: 958972464858.dkr.ecr.eu-north-1.amazonaws.com/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          envFrom:
            - secretRef:
                name: stagging-backend-env
---
apiVersion: v1
kind: Service
metadata:
  name: backend-staging-service
spec:
  type: LoadBalancer
  selector:
    app: backend
    environment: staging
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            key: access-key
          secretAccessKeySecretRef:
            name: aws-creds
            key: secret-access-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stagging-backend-env
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: stagging-backend-env
  dataFrom:
    - extract:
        key: stagging-backend-env